version: '3.1'
services:

  #database :postgresql
  postgresql:
    image: postgres:alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      #      - DB_SERVER=
      - POSTGRES_DB=userdatabase
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres


    #backend app
  spring-postgreql:
    container_name: spring-postgreql
    image: spring-postgreql
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "2009:8080"
    depends_on:
      - postgresql

      #frontend UI :React
      #frontend:
      #build :
      #context :./
      #port:
      #4000:4000
      #link:
      #-postgreSQL



