version: '3.1'
services:

  db:
    image: postgres:alpine
    container_name: database-postgresql

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

    #backend app
  admin-backend:
    container_name: app
    image: admin-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

      #frontend UI :React
      #frontend:
      #build :
      #context :./
      #port:
      #4000:4000
      #link:
      #-postgreSQL
