version: "3.8"
services:
  demo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_frontend
    ports:
      - "3000:3000"
    image:
      demo_frontend
    command: npm start
